---
- name: Install ufw
  pacman: name=ufw state=present
  tags: ufw

- name: Deny everything
  ufw: policy=deny
  tags: ufw

- name: Enable UFW with logging
  ufw:
    state: enabled
    logging: "on"
  tags: ufw

- name: Enable UFW service
  service: name=ufw.service enabled=yes state=started
