---
- name: Setup networkmanager
  include_tasks: networkmanager.yml
  when: inventory_hostname in groups['laptop']

- name: Setup firewall
  include_tasks: firewall.yml
  tags: ufw

- name: Install nmap
  pacman: name=nmap state=present

- name: fail2ban
  pacman: name=fail2ban state=present
  when: inventory_hostname in groups['backup']

- name: Ensure fail2ban is started
  service: name=fail2ban.service state=started
  when: inventory_hostname in groups['backup']

- name: Copy fail2ban configuration into place
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: u=rw,g=r,o=r
  notify: restart fail2ban
  when: inventory_hostname in groups['backup']

- name: Install wget
  pacman: name=wget state=present
