---
- name: Install NetworkManager and dependencies
  pacman:
    state: present
    name:
      - networkmanager
      - network-manager-applet

- name: Install VPN clients
  pacman:
    state: present
    name:
      - networkmanager-openvpn
      - networkmanager-vpnc
