---
- name: Install NetworkManager and dependencies
  pacman:
    state: present
    name:
      - networkmanager
      - network-manager-applet

- name: Enable and start NetworkManager
  service: name=NetworkManager.service enabled=yes state=started

- name: Install VPN clients
  pacman:
    state: present
    name:
      - networkmanager-openvpn
      - networkmanager-vpnc
