---
- name: Install NetworkManager and dependencies
  pacman: name={{ item }} state=present
  with_items:
      - networkmanager
      - network-manager-applet

- name: Install VPN clients
  pacman: name={{ item }} state=present
  with_items:
      - networkmanager-openvpn
      - networkmanager-vpnc
