---
- name: Install OpenSSH
  pacman: name=openssh state=present

- name: Set firewall rules for SSH
  ufw: rule=limit app=SSH
  tags: ufw

- name: Push OpenSSH daemon configuration file
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: u=rw,g=r,o=r
  notify: restart sshd

- name: SSHD options
  copy:
    dest: /etc/ssh/sshd_config.d/50-forwards.conf
    content: "StreamLocalBindUnlink yes"
  notify: reload sshd

- name: Enable and start OpenSSH
  service: name=sshd.service enabled=yes state=started

- name: Install sshfs
  pacman: name=sshfs state=present

- name: Install Mosh
  pacman: name=mosh state=present

- name: Set firewall rule for mosh
  ufw: rule=limit port=60000:61000 proto=udp
  tags: ufw
