---
- name: Install imagemagick and dependencies
  pacman:
    state: present
    name:
      - libraw
      - libpng
      - librsvg
      - openjpeg2
      - imagemagick
  tags:
    - imagemagick

- name: Install GIMP
  pacman:
    state: present
    name:
      - gimp
      - gimp-plugin-gmic
  tags:
    - gimp

- name: Install Inkscape
  pacman:
    name: inkscape
    state: present
  tags:
    - inkscape
    - pstoedit # latex renderer
    - pdf2svg

- name: Install Digikam
  pacman:
    state: present
    name:
      - digikam
      - enblend-enfuse # for image stacking
      - hugin # panorama stitcher
  tags:
    - digikam

- name: Install gThumb
  pacman:
    name: gthumb
    state: present
  tags:
    - gthumb

- name: Install vlc
  pacman:
    state: present
    name:
      - vlc

- name: Install libtaginfo
  pacman:
    name: libtaginfo
    state: present

- name: Install kdenlive
  pacman:
    state: present
    name:
      - kdenlive
      - frei0r-plugins

- name: Install OBS
  pacman:
    state: present
    name:
      - obs-studio
      - linux-headers
      - v4l2loopback-dkms

- name: Install tools for webcam
  pacman:
    state: present
    name:
      - bc
      - zenity
      - android-tools
