---
- name: Install imagemagick and dependencies
  pacman: name={{ item }} state=present
  with_items:
    - libraw
    - libpng
    - librsvg
    - openjpeg2
    - imagemagick
  tags:
    - imagemagick

- name: Install GIMP
  pacman: name={{ item }} state=present
  with_items:
    - gimp
    - gimp-plugin-gmic
  tags:
    - gimp

- name: Install Inkscape
  pacman: name=inkscape state=present
  tags:
    - inkscape
    - pstoedit # latex renderer
    - pdf2svg

- name: Install Digikam
  pacman: name={{ item }} state=present
  with_items:
    - digikam
    - kipi-plugins
  tags:
    - digikam

- name: Install gThumb
  pacman: name=gthumb state=present
  tags:
    - gthumb

- name: Install Okular
  pacman: name=okular state=present

- name: Install vlc
  pacman: name={{ item }} state=present
  with_items:
    - vlc
    - qt4

- name: Install mpd
  pacman: name=mpd state=present

- name: Install libtaginfo
  pacman: name=libtaginfo state=present

- name: Install amarok
  pacman: name=amarok state=present
