---
- name: Install imagemagick and dependencies
  pacman:
    state: present
    name:
      - libraw
      - libpng
      - librsvg
      - openjpeg2
      - imagemagick
  tags:
    - imagemagick

- name: Install GIMP
  pacman:
    state: present
    name:
      - gimp
      - gimp-plugin-gmic
  tags:
    - gimp

- name: Install Inkscape
  pacman:
    name: inkscape
    state: present
  tags:
      - inkscape
      - pstoedit # latex renderer
      - pdf2svg

- name: Install Digikam
  pacman:
    state: present
    name:
      - digikam
      - kipi-plugins
      - enblend-enfuse # for image stacking
      - hugin # panorama stitcher
  tags:
    - digikam

- name: Install gThumb
  pacman:
    name: gthumb
    state: present
  tags:
    - gthumb

- name: Install Okular
  pacman:
    name: okular
    state: present

- name: Install vlc
  pacman:
    state: present
    name:
      - vlc

- name: Install mpd
  pacman:
    name: mpd
    state: present

- name: Install libtaginfo
  pacman:
    name: libtaginfo
    state: present

- name: Install kdenlive
  pacman:
    state: present
    name:
      - kdenlive
      - frei0r-plugins
