language: python
python:
  - "3.6"
install:
  - pip install ansible ansible-lint
script:
  - ansible-playbook install.yml -i hosts --syntax-check
  - ansible-lint -x ANSIBLE0004,ANSIBLE0009 install.yml
