---
- hosts: laptop
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: cron, tags: ['cron'] }
    - { role: networkmanager, tags: ['networkmanager'] }
    - { role: x, tags: ['x'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: backup, tags: ['backup'] }
    - { role: awesome, tags: ['awesome'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: editors, tags: ['editors'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: office, tags: ['office'] }
    - { role: spell, tags: ['spell'] }
    - { role: sound, tags: ['sound'] }
    - { role: bluetooth, tags: ['bluetooth'], when: "bluetooth is defined" }
    - { role: multimedia, tags: ['multimedia'] }
    - { role: python, tags: ['python'] }
    - { role: ruby, tags: ['ruby'] }
    - { role: numerical, tags: ['numerical'] }
    - { role: secrets, tags: ['secrets'] }
    - { role: yubikey, tags: ['yubikey'] }
    - { role: servers, tags: ['servers'] }

    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: mail, tags: ['mail'] }
    - { role: cloudservices, tags: ['cloudservices'] }
