---
- hosts: laptop
  become: yes
  roles:
    - base
    - { role: cron, tags: ['cron'] }
    - { role: networkmanager, tags: ['networkmanager'] }
    - x
    - { role: ssh, tags: ['ssh'] }
    - { role: backup, tags: ['backup'] }
    - { role: awesome, tags: ['awesome'] }
    - { role: browsers, tags: ['browsers'] }
    - editors
    - fonts
    - office
    - { role: spell, tags: ['spell'] }
    - { role: sound, tags: ['sound'] }
    - { role: multimedia, tags: ['multimedia'] }
    - python
    - secrets
    - yubikey

    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: mail, tags: ['mail'] }
