---
- hosts: laptop
  become: yes
  roles:
    - base
    - { role: cron, tags: ['cron'] }
    - networkmanager
    - x
    - { role: ssh, tags: ['ssh'] }
    - awesome
    - browsers
    - editors
    - fonts
    - office
    - { role: spell, tags: ['spell'] }
    - { role: sound, tags: ['sound'] }
    - python
    - secrets
    - yubikey
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: mail, tags: ['mail'] }
