---
- hosts: laptop
  become: yes
  roles:
    - base
    - networkmanager
    - x
    - awesome
    - browsers
    - editors
    - fonts
    - office
    - { role: sound, tags: ['sound'] }
    - python
    - secrets
    - yubikey
