---
- hosts: laptop
  become: yes
  gather_facts: True
  roles:
    - { role: base, tags: ["base"] }
    - { role: cron, tags: ["cron"] }
    - { role: networking, tags: ["networking"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: x, tags: ["x"] }
    - { role: secrets, tags: ["secrets"] }
    - { role: development, tags: ["development"] }
    - { role: spell, tags: ["spell"] }
    - { role: fonts, tags: ["fonts"] }
    - { role: multimedia, tags: ["multimedia"] }
    - { role: sound, tags: ["sound"] }
    - { role: bluetooth, tags: ["bluetooth"], when: "bluetooth is defined" }

    # User work stuff
    #- { role: c_cpp, tags: ["c_cpp"] }
    #- { role: numerical, tags: ["numerical"] }
    - { role: languages, tags: ["languages"] }
    - { role: servers, tags: ["servers"] }
    # - { role: arduino, tags: ["arduino"] }
    - { role: monitoring, tags: ["monitoring"] }
    - {
        role: postgresql,
        tags: ["postgres"],
        postgres_tls_method: "self-signed",
      }

    # User stuff maybe better as dotfiles
    - { role: office, tags: ["office"] }
    - { role: browsers, tags: ["browsers"] }
    - { role: dotfiles, tags: ["dotfiles"] }

    - {
        role: cardano,
        tags: ["cardano"],
        dbs: ["mainnet", "testnet"],
        networks: [{ desc: "Mainnet", name: "mainnet", port: "3001" }],
      }

    - {
        role: bitcoin,
        tags: ["bitcoin"],
        networks:
          [
            {
              name: "bitcoin",
              datadir: "/mnt/disk/bitcoind/",
              extra_args: "",
              btc_rpc: 8332,
              electrs_rpc: 50002,
              electrs_prom: 24225,
            },
            {
              name: "testnet",
              datadir: "/mnt/disk/bitcoind/",
              extra_args: "-testnet",
              btc_rpc: 18332,
              electrs_rpc: 50003,
              electrs_prom: 24226,
            },
            {
              name: "regtest",
              datadir: "/mnt/disk/bitcoind/",
              extra_args: "-regtest",
              btc_rpc: 18443,
              electrs_rpc: 50004,
              electrs_prom: 24227,
            },
          ],
      }
