---
- hosts: laptop
  become: yes
  roles:
    - { role: base, tags: ["base"] }
    - { role: cron, tags: ["cron"] }
    - { role: networking, tags: ["networking"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: x, tags: ["x"] }
    - { role: secrets, tags: ["secrets"] }
    - { role: development, tags: ["development"] }
    - { role: spell, tags: ["spell"] }
    - { role: fonts, tags: ["fonts"] }
    - { role: multimedia, tags: ["multimedia"] }
    - { role: sound, tags: ["sound"] }
    - { role: bluetooth, tags: ["bluetooth"], when: "bluetooth is defined" }

    # User stuff maybe better as dotfiles
    - { role: office, tags: ["office"] }
    - { role: browsers, tags: ["browsers"] }
    - { role: dotfiles, tags: ["dotfiles"] }

    # User work stuff
    #- { role: c_cpp, tags: ["c_cpp"] }
    #- { role: numerical, tags: ["numerical"] }
    - { role: languages, tags: ["languages"] }
    - { role: servers, tags: ["servers"] }
    # - { role: arduino, tags: ["arduino"] }
