---
- hosts: raspberry
  user: root
  roles:
    - { role: base, tags: ['base'] }
    - { role: cron, tags: ['cron'] }
    - { role: networking, tags: ['networking'] }
    - { role: ssh, tags: ['ssh'] }
