---
- hosts: raspberry
  user: alarm
  become: True
  tasks:
    - name: "Set authorized interact key"
      authorized_key:
        user: "alarm"
        state: present
        key: "{{ lookup('file', 'roles/base/files/nitro_smart.pub') }}"
      tags: ssh
  roles:
    - { role: base, tags: ["base"] }
    - { role: networking, tags: ["networking"] }
    - { role: backup, tags: ["backup"], repo_path: "/media/Backup/" }
    - {
        role: monitoring,
        tags: ["monitoring"],
        monitoring_server: "192.168.178.26",
      }
