---
- hosts:
    - nina
  user: orchest
  become: True
  roles:
    - { role: base, tags: ["base"] }
    - { role: networking, tags: ["networking", "ssh"] }
    - { role: backup, tags: ["backup"], repo_path: "/home/borgbackup/repos/" }
    - { role: monitoring, tags: ["monitoring"] }

- hosts: nina
  user: orchest
  become: True
  roles:
    - {
        role: bitcoin,
        tags: ["bitcoin"],
        pruned: 5500,
        manual: false,
        lnd_port: 9735,
        lnd_rest_port: 8480,
        networks: [
            {
              name: "bitcoin",
              datadir: "/var/lib/bitcoind/",
              extra_args: "",
              daemon_args: "",
              btc_rpc: 8332,
              electrs_rpc: 50002,
              electrs_prom: 24225,
            },
            {
              name: "testnet",
              datadir: "/var/lib/bitcoind/",
              #https://github.com/lightningnetwork/lnd/issues/9053#issuecomment-2408658986
              extra_args: "-testnet",
              daemon_args: " -deprecatedrpc=warnings",
              btc_rpc: 18332,
              electrs_rpc: 50003,
              electrs_prom: 24226,
            },
            {
              name: "regtest",
              datadir: "/var/lib/bitcoind/",
              extra_args: "-regtest",
              daemon_args: "",
              btc_rpc: 18443,
              electrs_rpc: 50004,
              electrs_prom: 24227,
            },
          ],
      }
