---
- hosts:
    - backup
    - cardano
    - nina
  user: orchest
  become: True
  roles:
    - { role: base, tags: ["base"] }
    - { role: cron, tags: ["cron"] }
    - { role: networking, tags: ["networking"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: monitoring, tags: ["monitoring"] }

- hosts: backup
  user: orchest
  become: True
  roles:
    - { role: bitcoin, tags: ["bitcoin"] }

- hosts: cardano
  user: orchest
  become: True
  roles:
    - {
        role: postgres,
        tags: ["postgres"],
        dbs: ["mainnet", "testnet"],
        postgres_tls_method: "letsencrypt",
      }
    - { role: cardano, tags: ["cardano"], networks: [
            # { desc: "Mainnet", name: "mainnet", port: "3001" },
            { desc: "Testnet", name: "testnet", port: "3002" },
          ] }

- hosts: nina
  user: orchest
  become: True
  roles:
    - {
        role: cardano,
        tags: ["cardano"],
        networks: [{ desc: "Mainnet", name: "mainnet", port: "3001" }],
        postgres_host: "db.arsmagna.xyz",
      }
