---
- hosts:
    - backup
    - cardano
    - nina
  user: orchest
  become: True
  roles:
    - { role: base, tags: ["base"] }
    - { role: cron, tags: ["cron"] }
    - { role: networking, tags: ["networking"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: monitoring, tags: ["monitoring"] }

- hosts: backup
  user: orchest
  become: True
  roles:
    - { role: bitcoin, tags: ["bitcoin"] }

- hosts: cardano
  user: orchest
  become: True
  roles:
    - {
        role: postgresql,
        tags: ["postgres"],
        postgres_tls_method: "letsencrypt",
      }
    - {
        role: cardano,
        tags: ["cardano"],
        dbs: ["preview"],
        networks: [{ desc: "preview", name: "preview", port: "3002" }],
      }

- hosts: nina
  user: orchest
  become: True
  roles:
    - {
        role: cardano,
        tags: ["cardano"],
        dbs: ["mainnet"],
        networks: [{ desc: "Mainnet", name: "mainnet", port: "3001" }],
        # postgres_host: "db.arsmagna.xyz",
        cardano_db_pwd: "{{ lookup( 'password', 'pass/pgsql_cardano.pwd' ) }}",
      }
    - {
        role: postgresql,
        tags: ["postgres"],
        postgres_tls_method: "self-signed",
      }
