---
- hosts: backup
  user: orchest
  become: True
  roles:
    - { role: base, tags: ['base'] }
    - { role: cron, tags: ['cron'] }
    - { role: networking, tags: ['networking'] }
    - { role: ssh, tags: ['ssh'] }
