---
- hosts:
    - backup
    - cardano
  user: orchest
  become: True
  roles:
    - { role: base, tags: ["base"] }
    - { role: cron, tags: ["cron"] }
    - { role: networking, tags: ["networking"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: monitoring, tags: ["monitoring"] }

- hosts: backup
  user: orchest
  become: True
  roles:
    - { role: bitcoin, tags: ["bitcoin"] }
    - {
        role: cardano,
        tags: ["cardano"],
        networks: [{ desc: "Testnet", name: "testnet", port: "3002" }],
      }

- hosts: cardano
  user: orchest
  become: True
  roles:
    - { role: cardano, tags: ["cardano"] }
