---
- name: Create main user
  user:
    name: "{{ user.name }}"
    state: present
    create_home: yes
    shell: /usr/bin/zsh
    groups: video
    append: yes

- name: Clone Chemacs
  git:
    repo: https://github.com/plexus/chemacs2.git
    dest: /home/{{ user.name }}/.emacs.d
    accept_hostkey: yes
    update: no
    depth: 1
  become: yes
  become_user: "{{ user.name }}"

- name: Clone Doom-emacs
  git:
    repo: https://github.com/hlissner/doom-emacs.git
    dest: /home/{{ user.name }}/dev/doom-emacs
    accept_hostkey: yes
    update: no
    depth: 1
  become: yes
  become_user: "{{ user.name }}"

- name: Clone oh-my-zsh repo
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /home/{{ user.name }}/.oh-my-zsh
    depth: 1
  become: yes
  become_user: "{{ user.name }}"

