---
- name: Clone user dotfiles
  git:
    repo: "{{ dotfiles.url }}"
    dest: /home/{{ user.name }}/{{ dotfiles.destination }} accept_hostkey=yes
    update: no
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"

- name: Clone awesome user dotfiles
  git:
    repo: "{{ awesome_conf.url }}"
    dest: /home/{{ user.name }}/{{ awesome_conf.destination }} accept_hostkey=yes
    update: no
  when: awesome_conf is defined
  become: yes
  become_user: "{{ user.name }}"

- name: symlink awesome config
  file:
    path: /home/{{ user.name }}/.config/awesome
    src: /home/{{ user.name }}/{{ awesome_conf.destination }}
    state: link
  when: awesome_conf is defined

- name: configure Oh-My-Zsh
  include_tasks: ohmyzsh.yml

- name: Install backup script
  template:
    src: backup_sh.j2
    dest: "{{ backup_script_path }}"
    mode: 0700
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Set up backup cron
  cron:
    name: Backupserver
    hour: "10,14,18,22"
    minute: "5"
    job: "{{ backup_script_path }} > /tmp/borgbackup 2>&1"
    user: "{{ user.name }}"
