- name: Install bluetooth libraries and tools
  pacman:
    state: present
    name:
      - blueman
      - bluez
      - bluez-libs
      - bluez-utils
      - pulseaudio-alsa
      - pulseaudio-bluetooth
  notify:
    - restart pulse as user

- name: Unblock the bluetooth service
  service:
    name: "rfkill-block@bluetooth.service"
    enabled: no
    state: stopped
  when: not bluetooth.disable

- name: Block the bluetooth service
  service:
    name: "rfkill-block@bluetooth.service"
    enabled: yes
    state: started
  when: bluetooth.disable

- name: Enable and start the bluetooth service
  service:
    name: bluetooth.service
    enabled: yes
    state: started
  when: not bluetooth.disable

- name: Disable and stop the bluetooth service
  service:
    name: bluetooth.service
    enabled: no
    state: stopped
  when: bluetooth.disable
