---
- name: Install GCC
  pacman: name=gcc state=present

- name: Install GNU Debugger
  pacman: name=gdb state=present

- name: Install cmake
  pacman: name=cmake state=present

- name: Install clang
  pacman:
    name: clang
    state: present
