---
- name: Install Xorg
  pacman: name=xorg-server state=present

- name: Install Xinit
  pacman: name=xorg-xinit state=present

- name: Install xrandr
  pacman:
    state: present
    name:
      - xorg-xrandr
      - arandr

- name: Install xmodmap
  pacman: name=xorg-xmodmap state=present

- name: Install intel video hardware drivers
  pacman:
    state: present
    name:
      - libva-intel-driver
      - xorg-xbacklight
  when: ansible_product_name == "Aspire V3-572G"

- name: Install intel video hardware drivers
  pacman:
    state: present
    name:
      - vulkan-intel
      - intel-media-driver
      - libva-utils
      - intel-media-sdk

- name: Install mesa demos
  pacman: name=mesa-demos state=present

- name: Install Wacom tablet drivers
  pacman: name=xf86-input-wacom state=present

- name: Install awesome WM
  include_tasks: awesome.yml
  tags: awesome
