---
- name: Install Xorg
  pacman: name=xorg-server state=present

- name: Install Xinit
  pacman: name=xorg-xinit state=present

- name: Install xrandr
  pacman: name=xorg-xrandr state=present

- name: Install xmodmap
  pacman: name=xorg-xmodmap state=present

- name: Install intel video hardware drivers
  pacman: name={{ item }} state=present
  with_items:
    - xf86-video-intel
    - libva-intel-driver
  when: ansible_product_name == "Aspire V3-572G"

- name: Add user to video group
  user: name={{ user.name }} groups=video append=yes
