---
- name: Install Xorg
  pacman: name=xorg-server state=present

- name: Install Xinit
  pacman: name=xorg-xinit state=present

- name: Install xrandr
  pacman: name=xorg-xrandr state=present

- name: Install xmodmap
  pacman: name=xorg-xmodmap state=present

- name: Install video driver(s)
  pacman: name={{ item }} state=present
  with_items: "{{ video_drivers }}"

- name: Add user to video group
  user: name={{ user.name }} groups=video append=yes
