---
- name: Install Xorg
  pacman: name=xorg-server state=present

- name: Install Xinit
  pacman: name=xorg-xinit state=present

- name: Install xrandr
  pacman: name={{ item }} state=present
  with_items:
    - xorg-xrandr
    - arandr

- name: Install xmodmap
  pacman: name=xorg-xmodmap state=present

- name: Install intel video hardware drivers
  pacman: name={{ item }} state=present
  with_items:
    - xf86-video-intel
    - libva-intel-driver
    - xorg-xbacklight
  when: ansible_product_name == "Aspire V3-572G"

- name: Install nvidia video hardware drivers
  pacman: name={{ item }} state=present
  with_items:
    - nvidia
  when: ansible_product_name == "Aspire V3-572G"

- name: Nvidia Configuration
  template: src=xorg-nvidia.conf.j2 dest=/etc/X11/xorg.conf.d/20-nvidia.conf
  when: ansible_product_name == "Aspire V3-572G"

- name: Install mesa demos
  pacman: name=mesa-demos state=present

- name: Install Wacom tablet drivers
  pacman: name=xf86-input-wacom state=present

- name: Add user to video group
  user: name={{ user.name }} groups=video append=yes
