---
# Defines handlers applicable across all machines in the infrastructure.
- name: reload systemd daemon
  systemd:
    daemon_reload: yes

- name: restart bitcoind
  loop: "{{ bitcoin_networks.results | selectattr('changed', 'equalto', true) | map(attribute='item') | map(attribute='name') | list }}"
  service:
    name: bitcoind-{{ item }}.service
    state: restarted

- name: restart electrs
  loop: "{{ electrs_networks.results | selectattr('changed', 'equalto', true) | map(attribute='item') | map(attribute='name') | list }}"
  service:
    name: electrs-{{ item }}.service
    state: restarted
