---
# Defines handlers applicable across all machines in the infrastructure.

- name: restart bitcoind
  loop: "{{ bitcoin_networks.results | selectattr('changed', 'equalto', true) | map(attribute='item') | map(attribute='name') | list }}"
  service:
    name: bitcoind-{{ item }}.service
    state: restarted
