---
# Defines handlers applicable across all machines in the infrastructure.
- name: reload systemd daemon
  systemd_service:
    daemon_reload: true

- name: restart systemd users
  service:
    name: systemd-sysusers.service
    state: restarted

- name: restart systemd tmpfiles
  service:
    name: systemd-tmpfiles-setup.service
    state: restarted

- name: restart bitcoind
  loop: "{{ bitcoin_networks.results | selectattr('changed', 'equalto', true) | map(attribute='item') | map(attribute='name') | list }}"
  service:
    name: bitcoind-{{ item }}.service
    state: restarted

- name: restart electrs
  loop: "{{ electrs_networks.results | selectattr('changed', 'equalto', true) | map(attribute='item') | map(attribute='name') | list }}"
  service:
    name: electrs-{{ item }}.service
    state: restarted

- name: restart lnd
  service:
    name: lnd-testnet.service
    state: restarted
