---
- name: Install poppler
  pacman: name={{ item }} state=present
  with_items:
    - poppler
    - poppler-glib

- name: Install latex
  pacman: name=texlive-most state=present

- name: Install calibre
  pacman: name=calibre state=present

- name: Install xournal
  pacman: name=xournal state=present

- name: Install LibreOffice
  pacman: name=libreoffice-fresh state=present

- name: Install dictionary
  pacman: name=goldendict state=present
