---
- name: Install notmuch and isysc
  pacman:
    state: present
    name:
      - notmuch
      - isync
      - bogofilter

- name: Install Okular
  pacman:
    state: present
    name: okular

- name: Install poppler
  pacman:
    state: present
    name:
      - poppler
      - poppler-glib

- name: Install calibre
  pacman: name=calibre state=present

- name: Install xournal
  pacman: name=xournalpp state=present

- name: Install console dictionary
  pacman: name=sdcv state=present

- name: Install dictionary
  pacman: name=goldendict state=present

- name: Install languagetool
  pacman: name=languagetool state=present

- name: Install LibreOffice
  pacman: name=libreoffice-fresh state=present

- name: Install latex
  pacman: name=texlive-most state=present

- name: Install hugo
  pacman: name=hugo state=present

- name: Install ledger
  pacman: name=ledger state=present

- name: Install NextCloud
  pacman: name=nextcloud-client state=present

- name: Install keybase
  pacman: name=keybase-gui state=present
