---
- name: Install python
  pacman:
    state: present
    name:
      - ipython
      - python-pip
      - python2-pip
      - python-virtualenv
      - python-virtualenvwrapper
      - python-ipdb

- name: Prepare dev3 environment
  pip:
    name: ipython
    virtualenv: /home/{{ user.name }}/.virtualenvs/dev3
    virtualenv_site_packages: yes
    virtualenv_python: python3.6
  become: yes
  become_user: "{{ user.name }}"
