---
- name: Install borg
  pacman:
    state: present
    name:
      - python-llfuse
      - borg

- name: Create backup user
  user: name=borgbackup state=present

- name: Backup disk on raspberry
  ansible.posix.mount:
    path: "{{ repo_path }}"
    src: UUID=3b38fbc9-2b23-4803-a3e6-6bf467bbca39
    fstype: reiserfs
    state: present
  when: inventory_hostname in groups['raspberry']

- name: Create repository dir
  file:
    path: "{{ repo_path }}"
    state: directory
    owner: borgbackup
    group: borgbackup

- name: Set authorized key taken from file
  authorized_key:
    user: borgbackup
    state: present
    key: "{{ item }}"
    key_options: 'command="borg serve --restrict-to-path {{ repo_path }}",restrict'
  with_file:
    - "roles/base/files/nitro_smart.pub"
    - "roles/base/files/ingrid_root.pub"
