---
- name: Install OpenSSH
  pacman: name=openssh state=present

- name: Push OpenSSH daemon configuration file
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config

- name: Enable and start OpenSSH
  service: name=sshd.socket enabled=yes state=started

- name: Install sshfs
  pacman: name=sshfs state=present

- name: Install Mosh
  pacman: name=mosh state=present
