---
- name: Install Arduino
  pacman:
    state: present
    name:
      - arduino
      - arduino-avr-core

- name: Add {{ user.name }} to uucp & lock groups
  user: name={{ user.name }} groups=uucp,lock append=yes
