---
- name: Install Arduino
  pacman: name={{ item }} state=present
  with_items:
    - arduino
    - arduino-avr-core

- name: Add {{ user.name }} to uucp & lock groups
  user: name={{ user.name }} groups=uucp,lock append=yes
