---
# Defines tasks applicable for postgreSQL
- name: Install Postgres
  package:
    name:
      - postgresql
      - python-psycopg2
    state: present
  tags:
    - dependencies

- name: Ensure PostgreSQL data directory exists.
  file:
    path: "{{ postgresql_data_dir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: Ensure PostgreSQL database is initialized.
  command: "initdb --locale=en_US.UTF-8 -E UTF8 -D {{ postgresql_data_dir }}"
  when: not pgdata_dir_version.stat.exists
  become: true
  become_user: "{{ postgresql_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: Configure global settings.
  lineinfile:
    dest: "{{ postgresql_data_dir }}/postgresql.conf"
    regexp: "^#?{{ item.option }}.+$"
    line: "{{ item.option }} = '{{ item.value }}'"
    state: "{{ item.state | default('present') }}"
    mode: 0644
  with_items: "{{ postgresql_global_config_options }}"
  notify: restart postgresql

- name: Configure host based authentication (if entries are configured).
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_data_dir }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0600
  notify: restart postgresql
  when: postgresql_hba_entries | length > 0

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: postgresql.service
    state: started
    enabled: yes

- name: "Postgresql cardano role is created."
  postgresql_user:
    name: "{{ cardano_user }}"
    password: "{{ cardano_db_pwd }}"
    encrypted: yes
    state: present
    role_attr_flags: CREATEDB
  become_user: "{{ postgresql_user }}"
  become: yes

- name: "[PostgreSQL] - Cardano db sync database is created."
  postgresql_db:
    name: "{{ item.name }}"
    state: present
    owner: "{{ cardano_user }}"
  become_user: "{{ postgresql_user }}"
  become: yes
  with_items: "{{ networks }}"
