---
- name: Install Firefox
  pacman: name=firefox state=present
  tags:
    - firefox
    - firefox-developer-edition

- name: Install Chromium
  pacman: name=chromium state=present
  tags:
    - chromium

- name: Install bittorrent
  pacman: name=transmission-qt state=present
  tags:
    - bittorrent
