---
- name: Install development tools
  pacman:
    state: present
    name:
      - base-devel
      - git

- name: Install sudo
  pacman: name=sudo state=present
  tags:
    - sudo

- name: Add user to wheel group
  user: name={{ user.name }} groups=wheel append=yes
  tags:
    - sudo

- name: Copy sudo configuration
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    mode: 0440
    validate: 'visudo -cf %s'
  tags:
    - sudo

- name: Install editors
  pacman: name={{ item }} state=present
  with_items: "{{ editors }}"
