---
- name: Install development tools
  pacman:
    state: present
    name:
      - base-devel
      - git

- name: Install sudo
  pacman: name=sudo state=present
  tags:
    - sudo

- name: sudo configuration
  lineinfile:
    path: /etc/sudoers.d/{{ user.name }}
    line: '{{ user.name }} ALL=(ALL) ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  tags:
    - sudo

- name: Install editors
  pacman:
    state: present
    name: "{{ editors }}"
