---
- name: Install bitcoin core
  pacman:
    state: present
    name:
      - bitcoin-daemon
      - bitcoin-cli

- name: Directory permissions
  file:
    state: directory
    mode: 0710
    owner: bitcoin
    group: bitcoin
    path: "{{ item }}"
  loop:
    - /var/lib/bitcoind
    - /etc/bitcoin

- name: Push Bitcoin daemon configuration file
  template: src=bitcoin.conf.j2 dest=/etc/bitcoin/bitcoin.conf
  notify: restart bitcoind

- name: Bitcoin network service
  template:
    src: bitcoind.service.j2
    dest: /usr/lib/systemd/system/bitcoind-{{ item.name }}.service
  register: bitcoin_networks
  notify:
    - reload systemd daemon
    - restart bitcoind
  with_items: "{{ networks }}"

- name: Enable Bitcoin networks
  service:
    name: "bitcoind-{{ item.name }}.service"
    enabled: yes
    state: started
  with_items: "{{ networks }}"
  when: false

- name: Set firewall rule bitcoin testnet
  ufw: rule=allow port=18333

# Add or modify nofile soft limit
- pam_limits:
    domain: bitcoin
    limit_type: soft
    limit_item: nofile
    value: 8192

- name: Install electrs
  copy:
    src: /home/titan/dev/bitcoin/electrs/target/release/electrs
    dest: /usr/bin
    mode: 755
  when: pruned == 0

- name: Create electrs dirs
  file:
    path: "{{ item.datadir }}/electrs/{{ item.name }}"
    owner: bitcoin
    group: bitcoin
    state: directory
    mode: 0755
  with_items: "{{ networks }}"
  when: pruned == 0

- name: Push Electrs daemon configuration file
  template: src=electrs-conf.toml.j2 dest={{ item.datadir }}electrs/{{ item.name }}/electrs-conf.toml
  register: electrs_networks
  notify:
    - reload systemd daemon
    - restart electrs
  with_items: "{{ networks }}"
  when: pruned == 0

- name: Electrs network service
  template:
    src: electrs.service.j2
    dest: /usr/lib/systemd/system/electrs-{{ item.name }}.service
  register: elects_networks
  notify:
    - reload systemd daemon
  with_items: "{{ networks }}"
  when: pruned == 0

- name: Setup LND
  import_tasks: lnd.yml
  tags: lnd
