---
- name: Install bitcoin core
  pacman:
    state: present
    name:
      # - bitcoin-daemon
      - jq # for cmk agent
      - vim # for cmk agent xxd

- name: Download bitcoin core node
  get_url:
    url: "https://bitcoincore.org/bin/bitcoin-core-27.1/bitcoin-27.1-x86_64-linux-gnu.tar.gz"
    dest: "{{ ansible_env.HOME }}/bitcoin-27.1-x86_64-linux-gnu.tar.gz"
    timeout: 300
    checksum: sha256:c9840607d230d65f6938b81deaec0b98fe9cb14c3a41a5b13b2c05d044a48422

- name: Decompress Bitcoin binaries
  unarchive:
    src: "{{ ansible_env.HOME }}/bitcoin-27.1-x86_64-linux-gnu.tar.gz"
    dest: "{{ ansible_env.HOME }}/"
    creates: "{{ ansible_env.HOME }}/bitcoin-27.1/bin/bitcoin-cli"
    remote_src: true

- name: Copy Bitcoin binaries
  copy:
    src: "{{ ansible_env.HOME }}/bitcoin-27.1/{{ item }}"
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  with_items:
    - bin/bitcoin-cli
    - bin/bitcoind

- name: Bitcoin user
  copy:
    dest: /usr/lib/sysusers.d/bitcoin.conf
    mode: "0644"
    content: "u bitcoin - - /var/lib/bitcoind\n"

- name: bitcoin dirs
  copy:
    dest: /usr/lib/tmpfiles.d/bitcoin.conf
    mode: "0644"
    content: |
      d /var/lib/bitcoind 0710 bitcoin bitcoin - -
      d /etc/bitcoin     0710 bitcoin bitcoin - -

- name: set swapiness
  sysctl:
    name: vm.swappiness
    value: "10"

- name: Directory permissions
  file:
    state: directory
    mode: 0710
    owner: bitcoin
    group: bitcoin
    path: "{{ item }}"
  loop:
    - /var/lib/bitcoind
    - /etc/bitcoin

- name: Bitcoin network service
  template:
    src: bitcoind.service.j2
    dest: /etc/systemd/system/bitcoind-{{ item.name }}.service
  register: bitcoin_networks
  notify:
    - reload systemd daemon
    # - restart bitcoind
  with_items: "{{ networks }}"

- name: Push Bitcoin daemon configuration file
  template: src=bitcoin.conf.j2 dest=/etc/bitcoin/bitcoin.conf
  notify: restart bitcoind

- name: Enable Bitcoin networks
  service:
    name: "bitcoind-{{ item.name }}.service"
    enabled: yes
    state: started
  with_items: "{{ networks }}"
  when: false

- name: Set firewall rule bitcoin testnet
  ufw: rule=allow port=18333

# Add or modify nofile soft limit
- pam_limits:
    domain: bitcoin
    limit_type: soft
    limit_item: nofile
    value: 8192
  when: false

- name: Install electrs
  copy:
    src: /home/titan/dev/bitcoin/electrs/target/release/electrs
    dest: /usr/bin
    mode: 755
  when: pruned == 0

- name: Create electrs dirs
  file:
    path: "{{ item.datadir }}/electrs/{{ item.name }}"
    owner: bitcoin
    group: bitcoin
    state: directory
    mode: 0755
  with_items: "{{ networks }}"
  when: pruned == 0

- name: Push Electrs daemon configuration file
  template: src=electrs-conf.toml.j2 dest={{ item.datadir }}electrs/{{ item.name }}/{{ item.name }}-conf.toml
  register: electrs_networks
  notify:
    - reload systemd daemon
    # - restart electrs
  with_items: "{{ networks }}"
  when: pruned == 0

- name: Electrs network service
  template:
    src: electrs.service.j2
    dest: /etc/systemd/system/electrs-{{ item.name }}.service
  register: elects_networks
  notify:
    - reload systemd daemon
  with_items: "{{ networks }}"
  when: pruned == 0

- name: Setup LND
  import_tasks: lnd.yml
  tags: lnd
