---
- name: Install bitcoin core Arch
  pacman:
    state: present
    name:
      - bitcoin-daemon
  when: not manual

- name: Install bitcoin core manually
  import_tasks: btc-manual.yml
  when: manual

- name: set swapiness
  sysctl:
    name: vm.swappiness
    value: "10"

- name: Directory permissions
  file:
    state: directory
    mode: 0770
    owner: bitcoin
    group: bitcoin
    path: "{{ item }}"
  loop:
    - "{{ datadir }}"
    - /etc/bitcoin

- name: Bitcoin network service
  template:
    src: bitcoind.service.j2
    dest: /etc/systemd/system/bitcoind-{{ item.name }}.service
  register: bitcoin_networks
  notify:
    - reload systemd daemon
    - restart bitcoind
  with_items: "{{ networks }}"

- name: Push Bitcoin daemon configuration file
  template: src=bitcoin.conf.j2 dest=/etc/bitcoin/bitcoin.conf
  notify: restart bitcoind

- name: Enable Bitcoin networks
  service:
    name: "bitcoind-{{ item.name }}.service"
    enabled: yes
    state: started
  with_items: "{{ networks }}"
  when: false

- name: Set firewall rule bitcoin testnet
  ufw: rule=allow port=18333

# Add or modify nofile soft limit
- pam_limits:
    domain: bitcoin
    limit_type: soft
    limit_item: nofile
    value: 8192
  when: false

- name: Setup Electrs
  import_tasks: electrs.yml
  tags: electrs
  # when: pruned == 0

- name: Setup LND
  import_tasks: lnd.yml
  tags: lnd
