---
# Defines handlers applicable across all machines in the infrastructure.

- name: restart fail2ban
  service: name=fail2ban.service state=restarted

- name: restart sshd
  service: name=sshd.service state=restarted
