cardano_db_pwd: "{{ lookup( 'password', 'pass/pgsql_cardano.pwd' ) }}"
postgresql_data_dir: "/var/lib/postgres/data"
postgresql_user: "postgres"
postgresql_group: "postgres"

postgres_host: db.arsmagna.xyz

# Host based authentication (hba) entries to be added to the pg_hba.conf. This
# variable's defaults reflect the defaults that come with a fresh installation.
postgresql_hba_entries:
  - { type: local, database: all, user: all, auth_method: peer }
  - {
      type: hostssl,
      database: all,
      user: all,
      address: "127.0.0.1/32",
      auth_method: "scram-sha-256",
    }
