---
- name: Copy pacman configuration file
  template: src=pacman.conf.j2 dest=/etc/pacman.conf

- name: Full system upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- include_tasks: shell.yml
- include_tasks: sudo.yml
- include_tasks: packages.yml

- name: Install Power management
  pacman: name={{ item }} state=present
  with_items:
    - acpid
    - acpi
    - powertop
  tags:
    - power

- name: Enable ACPID
  service: name=acpid.service enabled=yes
  tags:
    - power
