---
- name: Copy pacman configuration file
  template: src=pacman.conf.j2 dest=/etc/pacman.conf

- name: Full system upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install shells
  include_tasks: shell.yml

- name: Install universal base packages
  pacman:
    state: present
    name:
      - binutils
      - python
      - rsync
      - tree
      - mlocate
      - htop
  tags:
    - packages

- name: Ensure locale en_US.UTF-8 locale is present
  locale_gen:
    name: en_US.UTF-8
    state: present
- name: Set local en_US.UTF-8 locale systemwide
  copy:
    dest: "/etc/locale.conf"
    content: "LANG=en_US.UTF-8"

- name: set timezone to Europe/Berlin
  timezone:
    name: Europe/Berlin

- name: Install Power management
  pacman:
    state: present
    name:
      - acpid
      - acpi
      - powertop
  tags:
    - power

- name: Enable ACPID
  service: name=acpid.service enabled=yes
  tags:
    - power

- name: Enable fstrim for ssd
  service: name=fstrim.timer enabled=yes

- name: Install smartmontools
  pacman: name=smartmontools state=present

- name: Install Intel microcode
  pacman: name=intel-ucode state=present
  when: '"GenuineIntel" in ansible_processor'
