---
- name: Copy pacman configuration file
  template: src=pacman.conf.j2 dest=/etc/pacman.conf
  when: inventory_hostname in groups['laptop']

- name: Full system upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install shells
  include_tasks: shell.yml

- name: Install universal base packages
  pacman:
    state: present
    name:
      - binutils
      - python
      - rsync
      - tree
      - mlocate
      - htop
  tags:
    - packages

- name: Install Power management
  pacman:
    state: present
    name:
      - acpid
      - acpi
      - powertop
  tags:
    - power

- name: Enable ACPID
  service: name=acpid.service enabled=yes
  tags:
    - power

- name: Enable fstrim for ssd
  service: name=fstrim.timer enabled=yes

- name: Install smartmontools
  pacman: name=smartmontools state=present

- name: Install Intel microcode
  pacman: name=intel-ucode state=present
  when: '"GenuineIntel" in ansible_processor'
