---
- name: Copy pacman configuration file
  template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    mode: u=rw,g=r,o=r

- name: Full system upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install shells
  include_tasks: shell.yml

- name: Install universal base packages
  pacman:
    state: present
    name:
      - binutils
      - python
      - rsync
      - tree
      - mlocate
      - htop
      - ntp
  tags:
    - packages

- name: Ensure locale en_US.UTF-8 locale is present
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set local en_US.UTF-8 locale systemwide
  copy:
    dest: "/etc/locale.conf"
    content: "LANG=en_US.UTF-8"
    mode: u=rw,g=r,o=r

- name: set timezone to Europe/Berlin
  timezone:
    name: Europe/Berlin

- name: Power saving setup
  include_tasks: power.yml
  when: inventory_hostname in groups['laptop']

- name: Hardware
  include_tasks: hardware.yml
  when: inventory_hostname in groups['laptop']

- name: Install borg
  pacman:
    state: present
    name:
      - python-llfuse
      - borg
