---
- name: Install borg
  pacman:
    state: present
    name:
      - python-llfuse
      - borg

- name: Create backup user
  user: name=borgbackup state=present
  tags: back

- name: Set authorized key taken from file
  authorized_key:
    user: borgbackup
    state: present
    key: "{{ item }}"
    key_options: 'command="borg serve --restrict-to-path /home/borgbackup/repos/",restrict'
  with_file:
    - nitro_smart.pub
    - ingrid_root.pub
  tags: back
