---
# Defines handlers applicable across all machines in the infrastructure.

- name: restart rrdcached
  service: name=rrdcached.service state=restarted

- name: restart collectd
  service: name=collectd.service state=restarted
