---
- name: Install alsa-utils
  pacman:
    name: alsa-utils
    state: present

- name: Install Gstreamer
  pacman:
    state: present
    name:
      - gstreamer
      - gst-libav
      - gst-plugins-base

- name: Install PulseAudio
  pacman:
    state: present
    name:
      - pulseaudio
      - pavucontrol
      - gst-plugins-good

- name: Switch output to newly connected devices
  lineinfile:
    dest: /etc/pulse/default.pa
    state: present
    line: "load-module module-switch-on-connect"
