---
- name: reload systemd daemon
  systemd:
    daemon_reload: yes

- name: restart preview
  service:
    name: cardano-node-preview
    state: restarted

- name: restart db-sync preview
  service:
    name: cardano-db-sync-preview
    state: restarted

- name: restart mainnet
  service:
    name: cardano-node-mainnet
    state: restarted

- name: restart db-sync mainnet
  service:
    name: cardano-db-sync-mainnet
    state: restarted
