---
- name: restart cardano node
  loop: "{{ cardano_networks.results | selectattr('changed', 'equalto', true) | map(attribute='item') | map(attribute='name') | list }}"
  service:
    name: cardano-node-{{ item }}.service
    state: restarted

- name: restart cardano db-sync
  loop: "{{ cardano_db_sync.results | selectattr('changed', 'equalto', true) | map(attribute='item') | map(attribute='name') | list }}"
  service:
    name: cardano-db-sync-{{ item }}.service
    state: restarted
