---
- name: reload systemd daemon
  systemd:
    daemon_reload: yes

- name: restart alonzo-purple
  service:
    name: cardano-node-alonzo-purple
    state: restarted

- name: restart testnet
  service:
    name: cardano-node-testnet
    state: restarted

- name: restart mainnet
  service:
    name: cardano-node-mainnet
    state: restarted

- name: restart postgresql
  service:
    name: postgresql
    state: restarted
    sleep: 5
