---
- name: reload systemd daemon
  systemd:
    daemon_reload: yes

- name: restart testnet
  service:
    name: cardano-node-testnet
    state: restarted

- name: restart db-sync testnet
  service:
    name: cardano-db-sync-testnet
    state: restarted

- name: restart mainnet
  service:
    name: cardano-node-mainnet
    state: restarted

- name: restart db-sync mainnet
  service:
    name: cardano-db-sync-mainnet
    state: restarted
