---
- name: reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Restart all nodes
  notify:
    - restart {{ item.name }}
  with_items: "{{ networks }}"

- name: restart alonzo-purple
  service:
    name: cardano-node-alonzo-purple
    state: restarted

- name: restart testnet
  service:
    name: cardano-node-testnet
    state: restarted

- name: restart mainnet
  service:
    name: cardano-node-mainnet
    state: restarted
