---
- name: Install awesome WM
  pacman:
    state: present
    name:
      - awesome
      - xorg-server-xephyr

- name: Install display manager lightdm
  pacman: name=lightdm state=present
  pacman:
    state: present
    name:
      - lightdm
      - lightdm-webkit-theme-litarvan
      - numlockx
      - light-locker

- name: Write lightdm config
  template:
    src: lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf

- name: Write lightdm greeter config
  template:
    src: lightdm-webkit2-greeter.conf.j2
    dest: /etc/lightdm/lightdm-webkit2-greeter.conf

- name: Enable lightdm
  service: name=lightdm.service enabled=yes

- name: Install compton
  pacman: name=compton state=present

- name: Install RedShift and dependencies
  pacman:
    state: present
    name:
      - gtk3
      - python-gobject
      - python-xdg
      - redshift

- name: Configure geoclue to allow redshift
  blockinfile:
    path: /etc/geoclue/geoclue.conf
    block: |
      [redshift]
      allowed=true
      system=false
      users=
- name: Ensure redshift config dir exists
  file: path=/home/{{ user.name }}/.config/redshift state=directory

- name: Write redshift config
  template:
    src: redshift.conf.j2
    dest: /home/{{ user.name }}/.config/redshift/redshift.conf

- name: Install filesystem packages
  pacman:
    state: present
    name:
      - thunar
      - thunar-volman
      - gvfs # automount usb storage
      - gvfs-mtp # android storage
      - ark # archive zip extract
      - tumbler # image thumbnails
      - ffmpegthumbnailer

- name: Install termite
  pacman: name=termite state=present
  tags:
    - termite

- name: Install rofi
  pacman: name=rofi state=present
