---
- name: Install awesome WM
  pacman: name={{ item }} state=present
  with_items:
    - awesome
    - xorg-server-xephyr

- name: Install display manager SDDM
  pacman: name=sddm state=present

- name: Enable and start SDDM
  service: name=sddm.service enabled=yes state=started

- name: Install compton
  pacman: name=compton state=present

- name: Install filesystem packages
  pacman: name={{ item }} state=present
  with_items:
    - thunar
    - thunar-volman
    - gvfs # automount usb storage
    - gvfs-mtp # android storage
    - ark # archive zip extract
    - tumbler # image thumbnails
    - ffmpegthumbnailer

- name: Install screensaver
  pacman: name=xscreensaver state=present

- name: Install termite
  pacman: name=termite state=present
  tags:
    - termite
