---
- name: Install NetworkManager and dependencies
  pacman: name={{ item }} state=present
  with_items:
      - networkmanager
      - network-manager-applet

- name: Install VPN clients
  pacman: name={{ item }} state=present
  with_items:
      - networkmanager-openvpn
      - networkmanager-vpnc

- name: Install ufw
  pacman: name=ufw state=present

- name: Deny everything
  ufw: policy=deny
  tags: ufw

- name: Set firewall rules for SSH
  ufw: rule=limit app=SSH
  tags: ufw

- name: Enable UFW
  ufw: state=enabled
  tags: ufw
