---
- name: Install nodejs
  pacman:
    state: present
    name:
      - nodejs
      - npm
      - eslint
      - prettier
  tags: javascript

- name: Install python
  pacman:
    state: present
    name:
      - ipython
      - python-pip
      - python2-pip
      - python-virtualenv
      - python-virtualenvwrapper
      - python-ipdb
  tags: python

- name: Install clojure
  pacman:
    state: present
    name:
      - clojure
  tags: clojure

- name: Install leiningen
  pacman:
    name: leiningen
  tags: clojure

- name: Install GCC
  pacman: name=gcc state=present

- name: Install GNU Debugger
  pacman: name=gdb state=present

- name: Install cmake
  pacman: name=cmake state=present

- name: Install clang
  pacman:
    name: clang
    state: present

- name: Install Guile
  pacman:
    name:
      - guile
      - nyacc
  tags: guile

- name: Install shell formatter
  pacman:
    name: shfmt
    state: present
  tags: sh
