---
- name: Install nodejs
  pacman:
    state: present
    name:
      - nodejs
      - npm
      - eslint
      - prettier
  tags: javascript
  when: "'javascript' in activate"

- name: Install python
  pacman:
    state: present
    name:
      - ipython
      - python-pip
      - python-virtualenv
      - python-virtualenvwrapper
      - python-ipdb
  tags: python
  when: "'python' in activate"

- name: Intall python dev
  pacman:
    state: present
    name:
      - python-black
      - python-pytest
      - python-isort
      - python-pyflakes
      - python-pipenv
      - python-nose
  tags: python
  when: "'python' in activate"

- name: Install clojure
  pacman:
    state: present
    name:
      - clojure
      - leiningen
  tags: clojure
  when: "'clojure' in activate"

- name: Install GCC
  pacman: name=gcc state=present

- name: Install GNU Debugger
  pacman: name=gdb state=present

- name: Install cmake
  pacman: name=cmake state=present

- name: Install clang
  pacman:
    name: clang
    state: present

- name: Install Guile
  pacman:
    name:
      - guile
  tags: guile
  when: "'guile' in activate"

- name: Install shell formatter
  pacman:
    name: shfmt
    state: present
  tags: sh

- name: Install SBCL
  pacman:
    state: present
    name: sbcl
  tags: common-lisp
  when: "'lisp' in activate"
