---
- name: Install ansible tools
  pacman:
    state: present
    name:
      - python-passlib # pass management on remotes
      - python-netaddr # ipwrap filter for remotes

- name: Install Virtualbox
  pacman:
    state: present
    name:
      - net-tools
      - virtualbox-host-modules-arch
      - virtualbox-guest-iso
      - virtualbox

- name: Add the user to vboxusers group
  user: name={{ user.name }} groups=vboxusers append=yes

- name: Install vagrant
  pacman: name=vagrant state=present

- name: Install docker
  pacman:
    state: present
    name:
      - docker
      - docker-compose
# - name: Enable and start docker socket
#   service: name=docker.socket enabled=yes state=started
# Don't put the user in docker group because is root equivalent
