---
- name: Install core fonts
  pacman: name={{ item }} state=present
  with_items:
      - terminus-font
      - noto-fonts
      - ttf-dejavu
      - ttf-liberation
      - ttf-droid
      - ttf-ubuntu-font-family

- name: Install Font-Awesome
  pacman: name={{ item }} state=present
  with_items:
    - otf-font-awesome
    - ttf-font-awesome
