---
- name: Install core fonts
  pacman: name={{ item }} state=present
  with_items:
      - terminus-font
      - noto-fonts
      - ttf-dejavu
      - ttf-liberation
      - ttf-droid
      - ttf-ubuntu-font-family
